### ISSUE TITLE
`solito-universal-app-template-nativebase-typescript` - example "user detail" link does not work on native (works on web)

### ISSUE THREAD

**Issue by Dchyk** [GeekyAnts/nativebase-templates#63]
Cloned the "Solito universal app typescript" repo and installed, and I haven't changed anything in code yet - when I click on "open user detail" in iOS, the below error is thrown. When running the web app, the link navigates to the user detail page as expected. 

I'm new to Solito and haven't yet gone through how the react navigation is setup, though it looks correct at a glance - but am I missing something with the setup here?

<img width="390" alt="Screen Shot 2022-08-04 at 9 39 16 PM" src="https://user-images.githubusercontent.com/25135946/182983747-23b77ff3-3159-4786-a296-d1e23b20b1b6.png">

<img width="401" alt="Screen Shot 2022-08-04 at 9 38 10 PM" src="https://user-images.githubusercontent.com/25135946/182983664-9887bdaa-e6f8-4781-be49-422c1397a41d.png">

**Comment by AdarshJais** [comment]
Any update on this?

**Comment by ankit-tailor** [comment]
Hey @Dchyk @AdarshJais, Thanks for reporting the issue. We'll look into it,
